# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fd993159095d7830c439d02c5100b276dbaf35a6e52ae9e8d87ad264cfda942329ffa808ec6a46b772ff07efc97461bc67f4a21bc82994b0b3d37cdd5017d65

test:
  secret_key_base: aca5532021e946cc0f26954e0c9b0522e46de44dc467851d7edbfb0c18e7e4a934f1908197ce86bec4c15a7fe7b6a5b11ecd40b12c3c8e4a5e69d27211277564

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
